### ISSUE TITLE
Reimagine what this cookbook could be

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/ruby#14]
Right now it installs 100% unsupported Ruby versions and does so with a nasty definition file.  What would we want out of a ruby provider and a ruby recipe?

**Comment by lamont-granquist** [comment]
https://supermarket.chef.io/cookbooks/sk_ruby

- I haven't tested it with latest 2.1.6 and 2.2.3 and such.
- sk_ruby_symlinks can and should be moved to a property of the sk_ruby resource

i believe both of the BUGS in the README were fixed in chef awhile back and could be cleaned up.

could be extracted out into a general purpose build-from-sources-package-into-deb/rpm-use-s3-as-a-cache ark-like wrapper around source builds.

**Comment by iennae** [comment]
With the deprecation of this cookbook, closing issues on this cookbook.
